name: BuyAbilities
version: 0.8.1
main: com.rcjrrjcr.bukkitplugins.buyabilitiesplugin.BuyAbilities
description: Allows the purchase of temporary abilities with iConomy money.
authors:
    - rcjrrjcr
commands:
    bab:
        description: Alias for buyab
        usage: /bab [categories|category|page|current|buy|rent|rentuse|info|help]
    
    buyab:
        description: Buy abilities via this command
        usage: /buyab [categories|category|page|current|buy|rent|rentuse|info|help]
        